<a href="https://colab.research.google.com/github/elyalipa/hello-world/blob/master/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задать вектора а и b, найти их сумму**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b=np.array([10, 0.2, 3])
a+b

array([11. ,  2.2,  6. ])

**Массив b преобразовать в массив комплексных чисел**

In [ ]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

**Создать числовую последовательность от 10 до 30 с шагом 5**

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

**Создать массив из 15 элементов. Развернуть его (первый становится последним).**

In [ ]:
Z = np.arange(15)
Z = Z[::-1]
Z

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Создать массив 10x10 со случайными значениями, найти минимум и максимум.**

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

(0.016098638025925704, 0.9946890410416266)

**Создать случайный вектор размера 30 и найти среднее значение всех элементов**

In [ ]:
Z = np.random.random(30)
m = Z.mean()
m

0.5029660948850491

**Создать объект Series, вывести на экран.**

In [ ]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

**DataFrame**

In [ ]:
import pandas as pd
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
     'population': [17.04, 143.5, 9.5, 45.5],
     'square': [2724902, 17125191, 207600, 603628]
 })
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

Чтобы убедиться, что столбец в DataFrame это Series, извлекаем любой:

In [ ]:
import pandas as pd
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
     'population': [17.04, 143.5, 9.5, 45.5],
     'square': [2724902, 17125191, 207600, 603628]
 })
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

**Математическик операции над объектом Series**

In [ ]:
# операция >
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series [my_series > 7]

3     8
4     9
5    10
dtype: int64

In [ ]:
# операция умножения
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series *2

0    10
1    12
2    14
3    16
4    18
5    20
dtype: int64

In [ ]:
# операция деления
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series /5

0    1.0
1    1.2
2    1.4
3    1.6
4    1.8
5    2.0
dtype: float64

**2. Создать таблицу из 3 столбцов, 5 строк.**


In [16]:
import pandas as pd
df = pd.DataFrame({
     'author': ['Адамс Дуглас', 'Гарри Гаррисон', 'Мариам Петросян', 'Говард Лавкрафт', 'Рю Мураками'],
     'book': ['Автостопом по галактике', 'Мир смерти', 'Дом, в котором', 'Изгой', 'Танатос'],
     'year': [1979, 1998, 2009, 1926, 2002]
 })
df

author                     book  year
0     Адамс Дуглас  Автостопом по галактике  1979
1   Гарри Гаррисон               Мир смерти  1998
2  Мариам Петросян           Дом, в котором  2009
3  Говард Лавкрафт                    Изгой  1926
4      Рю Мураками                  Танатос  2002